version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: barcode-buddy-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./barcode-buddy-1.sql:/docker-entrypoint-initdb.d/barcode-buddy-1.sql
    networks:
      - brownfleet-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: brownfleet-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - brownfleet-network
    depends_on:
      - postgres
    restart: unless-stopped

  api:
    image: ghcr.io/brownfleet/brownfleet-server:latest
    container_name: brownfleet-api
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BASE_URL=${BASE_URL}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - NODE_OPTIONS=--max-old-space-size=512
    networks:
      - brownfleet-network
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    restart: unless-stopped
    mem_limit: 1g
    memswap_limit: 2g

volumes:
  postgres_data:

networks:
  brownfleet-network:
    driver: bridge
