name: Build, Test & Deploy

on:
  push:
    branches: [main]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npm run type-check
      - name: Check formatting
        run: npm run format:check
      - name: Check circular dependencies
        run: npm run find-circulars
      - name: Run tests
        run: npm run test

  build-and-push:
    needs: ci-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/BrownFleet/brownfleet-server:latest .
          docker push ghcr.io/BrownFleet/brownfleet-server:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SSH for GitHub Actions → GCP VM
        run: |
          mkdir -p ~/.ssh/github-client-to-vm
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/github-client-to-vm/id_ed25519
          chmod 600 ~/.ssh/github-client-to-vm/id_ed25519
          ssh-keyscan -H ${{ secrets.GCP_HOST }} >> ~/.ssh/github-client-to-vm/known_hosts
      - name: Create .env file for deploy
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}" >> .env
          echo "NODE_ENV=production" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }}" >> .env
          echo "PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }}" >> .env
          echo "PGADMIN_PORT=${{ secrets.PGADMIN_PORT }}" >> .env
      - name: Copy .env to VM
        run: |
          scp -i ~/.ssh/github-client-to-vm/id_ed25519 -o StrictHostKeyChecking=no .env ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }}:~/brownfleet/.env
      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/github-client-to-vm/id_ed25519 -o UserKnownHostsFile=~/.ssh/github-client-to-vm/known_hosts -o ConnectTimeout=10 ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} <<-'EOF'
            set -e
            echo "Starting deployment..."
            mkdir -p ~/.ssh/vm-client-to-github
            ssh-keyscan -H github.com >> ~/.ssh/vm-client-to-github/known_hosts
            echo "Cloning or updating repository..."
            mkdir -p ~/brownfleet
            if [ ! -d ~/brownfleet/brownfleet-server/.git ]; then
              git clone git@github.com:BrownFleet/brownfleet-server.git ~/brownfleet/brownfleet-server
            fi
            cd ~/brownfleet/brownfleet-server
            git pull origin main
            echo "Cleaning up unused Docker resources..."
            sudo docker system prune -a -f --volumes
            echo "Logging in to GitHub Container Registry..."
            echo "${{ secrets.GH_PAT }}" | sudo docker login ghcr.io -u ${{ secrets.GH_USERNAME }} --password-stdin
            echo "Running docker-compose..."
            sudo docker-compose -f docker-compose.prod.yml --env-file ../.env down
            sudo docker-compose -f docker-compose.prod.yml --env-file ../.env pull
            sudo docker-compose -f docker-compose.prod.yml --env-file ../.env up -d
            echo "Deployment completed."
          EOF
